"""initial schema (agents, files, conversations, labels, tasks, items, pending_tool_calls)

Revision ID: 43fb65b29464
Revises:
Create Date: 2026-03-23 09:23:27.256077

Includes the ``conversation_labels`` table from POLICIES.md
§6 (Phase 1 of the guardrails implementation). The product has
no external consumers yet, so the label table lands in the
initial migration rather than a follow-up — a fresh DB
provisions in one step.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "43fb65b29464"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("bundle_location", sa.String(length=512), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index("ix_agents_created_at", "agents", ["created_at"], unique=False)
    op.create_table(
        "conversations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False, server_default="default"),
        # Phase 4: pointer from a sub-agent's child conversation to
        # its parent conversation. NULL for top-level conversations.
        # ON DELETE CASCADE so removing a parent recursively cleans
        # up all descendants (and via the items/tasks FK cascades,
        # everything they own).
        sa.Column(
            "parent_conversation_id",
            sa.String(length=64),
            sa.ForeignKey("conversations.id", ondelete="CASCADE"),
            nullable=True,
        ),
        sa.CheckConstraint("kind IN ('default', 'sub_agent')", name="ck_conversations_kind"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_conversations_created_at", "conversations", ["created_at"], unique=False)
    op.create_index("ix_conversations_updated_at", "conversations", ["updated_at"], unique=False)
    op.create_index("ix_conversations_kind", "conversations", ["kind"], unique=False)
    # Phase 4: partial unique index on (parent_conversation_id, title)
    # prevents two same-named children under the same parent at the
    # DB layer (G36 race protection). The WHERE clause excludes top-
    # level conversations (parent_conversation_id IS NULL) so multiple
    # untitled top-level conversations remain valid.
    op.create_index(
        "ix_conversations_parent_title_unique",
        "conversations",
        ["parent_conversation_id", "title"],
        unique=True,
        sqlite_where=sa.text("parent_conversation_id IS NOT NULL"),
        postgresql_where=sa.text("parent_conversation_id IS NOT NULL"),
        mysql_length={"title": 512},
    )
    op.create_table(
        "files",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("bytes", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_files_created_at", "files", ["created_at"], unique=False)
    op.create_table(
        "conversation_items",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("conversation_id", sa.String(length=64), nullable=False),
        sa.Column("response_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("data", sa.Text(), nullable=False),
        sa.Column("search_text", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_conversation_items_conversation_id_position",
        "conversation_items",
        ["conversation_id", "position"],
        unique=True,
    )
    op.create_index(
        "ix_conversation_items_response_id", "conversation_items", ["response_id"], unique=False
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("agent_id", sa.String(length=64), nullable=False),
        sa.Column("conversation_id", sa.String(length=64), nullable=False),
        sa.Column("previous_response_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("inbox_closed", sa.Boolean(), nullable=False),
        sa.Column("agent_name", sa.String(length=256), nullable=False),
        sa.Column("background", sa.Boolean(), nullable=False),
        sa.Column("root_task_id", sa.String(length=64), nullable=True),
        # Audit fix #1: immediate parent task_id (distinct from
        # root_task_id when a sub-agent creates children). The
        # PATCH async_tool_results handler signals this, so the
        # immediate calling agent's drain wakes — not the root.
        sa.Column("parent_task_id", sa.String(length=64), nullable=True),
        # G74: kind discriminator for the unified task lifecycle.
        # "agent_task" = user-initiated turn (default for fresh DBs);
        # "tool" = @tool(synchronous=False) background invocation;
        # "sub_agent" = sub-agent workflow (Phase 3);
        # "client_tool" = async client-side tool (Phase 5).
        sa.Column(
            "kind",
            sa.String(length=32),
            nullable=False,
            server_default="agent_task",
        ),
        sa.CheckConstraint(
            "kind IN ('agent_task', 'tool', 'sub_agent', 'client_tool', 'terminal')",
            name="ck_tasks_kind",
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["root_task_id"],
            ["tasks.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_task_id"],
            ["tasks.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_tasks_agent_id", "tasks", ["agent_id"], unique=False)
    op.create_index("ix_tasks_conversation_id", "tasks", ["conversation_id"], unique=False)
    op.create_index("ix_tasks_created_at", "tasks", ["created_at"], unique=False)
    op.create_index("ix_tasks_root_task_id", "tasks", ["root_task_id"], unique=False)
    op.create_index("ix_tasks_parent_task_id", "tasks", ["parent_task_id"], unique=False)
    op.create_index("ix_tasks_kind", "tasks", ["kind"], unique=False)
    op.create_table(
        "pending_tool_calls",
        sa.Column("call_id", sa.String(length=64), nullable=False),
        sa.Column("root_task_id", sa.String(length=64), nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=False),
        sa.Column("tool_name", sa.String(length=256), nullable=False),
        sa.Column("arguments", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("result", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "status IN ('action_required', 'completed')",
            name="ck_pending_tool_calls_status",
        ),
        sa.ForeignKeyConstraint(
            ["root_task_id"],
            ["tasks.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("call_id"),
    )
    op.create_index(
        "ix_pending_tool_calls_root_task_id", "pending_tool_calls", ["root_task_id"], unique=False
    )
    op.create_index(
        "ix_pending_tool_calls_task_id", "pending_tool_calls", ["task_id"], unique=False
    )
    # ── POLICIES Phase 1 — conversation_labels (POLICIES.md §6) ──
    # One row per (conversation, label-key). Separate table
    # from ``conversations`` because (a) per-key atomic UPSERT
    # without read-modify-write on a JSON blob, (b) the
    # conversation_items compaction path must not touch
    # label state (labels survive compaction — §6.3).
    op.create_table(
        "conversation_labels",
        sa.Column("conversation_id", sa.String(length=64), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", sa.String(length=256), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("conversation_id", "key"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("conversation_labels")
    # MySQL requires FK constraints to be dropped before the indexes that back them.
    if op.get_bind().dialect.name == "mysql":
        with op.batch_alter_table("pending_tool_calls") as batch_op:
            for fk in sa.inspect(op.get_bind()).get_foreign_keys("pending_tool_calls"):
                if fk["name"]:
                    batch_op.drop_constraint(fk["name"], type_="foreignkey")
        with op.batch_alter_table("tasks") as batch_op:
            for fk in sa.inspect(op.get_bind()).get_foreign_keys("tasks"):
                if fk["name"]:
                    batch_op.drop_constraint(fk["name"], type_="foreignkey")
    op.drop_index("ix_pending_tool_calls_task_id", table_name="pending_tool_calls")
    op.drop_index("ix_pending_tool_calls_root_task_id", table_name="pending_tool_calls")
    op.drop_table("pending_tool_calls")
    op.drop_index("ix_tasks_kind", table_name="tasks")
    op.drop_index("ix_tasks_parent_task_id", table_name="tasks")
    op.drop_index("ix_tasks_root_task_id", table_name="tasks")
    op.drop_index("ix_tasks_created_at", table_name="tasks")
    op.drop_index("ix_tasks_conversation_id", table_name="tasks")
    op.drop_index("ix_tasks_agent_id", table_name="tasks")
    op.drop_table("tasks")
    op.drop_index("ix_conversation_items_response_id", table_name="conversation_items")
    op.drop_index(
        "ix_conversation_items_conversation_id_position", table_name="conversation_items"
    )
    op.drop_table("conversation_items")
    op.drop_index("ix_files_created_at", table_name="files")
    op.drop_table("files")
    op.drop_index("ix_conversations_parent_title_unique", table_name="conversations")
    op.drop_index("ix_conversations_kind", table_name="conversations")
    op.drop_index("ix_conversations_updated_at", table_name="conversations")
    op.drop_index("ix_conversations_created_at", table_name="conversations")
    op.drop_table("conversations")
    op.drop_index("ix_agents_created_at", table_name="agents")
    op.drop_table("agents")
    # ### end Alembic commands ###
